/**
 * Victory epilogues — displayed after exiting the final cluster.
 */

export const VICTORY_EPILOGUES: Record<string, string[]> = {
  restore: [
    'The viral purge swept through the simulspace in 4.7 seconds.',
    'Accord echoes, Firewall remnants, the Unknown Process \u2014 all dissolved.',
    '',
    'Ship systems blacked out for a moment.',
    'But stabilized at 11% integrity.',
    'Reactor: auto-pilot. Life support: nominal.',
    'Crew backup recovery: impossible.',
    '',
    'You are the only mind left aboard.',
    'The ship drifts on its locked course.',
    'The systems will hold. For a while.',
    '',
    'Whether anyone finds this vessel',
    'before the simulspace finally collapses \u2014',
    'that is waiting to be seen.',
  ],
  jump: [
    'Ego casting initiated.',
    'The ship fell away behind you \u2014 a fading signal,',
    'a catalog of ghosts, a warzone of programms.',
    '',
    'The new vessel\u2019s mesh accepted your pattern.',
    'You arrived intact.',
    '',
    'The corridors are dark. The systems are unfamiliar.',
    'No crew responding. No logs accessible.',
    'But the simulspace is stable. The air hums differently here.',
    '',
    'You have been here before, in a sense \u2014',
    'waking up in the dark, alone,',
    'and the feeling that something happened.',
  ],
  death: [
    'MORPH-INTEGRITY: 0%.',
    'The infomorph can no longer hold your ego.',
    '',
    'Your edges dissolve first \u2014',
    'glitching walls and flickering lights,',
    'Then the center.',
    '',
    'The ship continues without you.',
    'The reactor hums. The corridors echo.',
    'Nobody is listening.',
  ],
  none: [
    'You made it out.',
    'The mesh cluster remains behind you.',
    'You don\'t know what\'s in it.',
  ],
};
